Data entry component
cornellh4i/clean-the-world pull request #18
Opened 2023-03-28 21:50 UTC by hanahhleee

## Overview

Closes #13 : We created a data entry component with the fields date (Date object), fog net id (string), cluster id (string), model name (string), and water collected (number). Upon clicking on the submit button, it displays the entered data in an alert.  

## Changes Made

The date field is auto-filled with today's date but can be changed to whatever date. This date is validated to make sure that the date is a real date. Water collected is validated to be a number, specifically a float, but note that if the inputted number is a decimal that ends in 0 (ex. 15.0), it will interpret the input as an integer.

## Test Coverage

1. checkout branch data-entry-component
2. If submit with empty field, alert that the field is missing
3. If date is not valid, alert that the date is invalid
4. If all fields filled out and valid, alert complete data entry

## Next Steps (delete if not applicable)

The next step would be to store the actual data that is entered into the database. Note that we may need to circle back to this if the lack of type float in js interferes with the data collection.

2023-03-28 22:35 UTC, jfeuerstein requested changes
Left a couple of comments (and made a few changes in person with you) -- looks great so far! Once you make these changes and push it should be good to go!

2023-03-28 22:35 UTC, jfeuerstein commented on mobile/components/CustomButton/CustomButton.tsx
> +  css: {},
Try using a safer type here
```suggestion
  css: object,
```

2023-03-28 22:35 UTC, jfeuerstein commented on mobile/components/CustomButton.tsx
> +  handleClick: () => {},
Try to make the typing a little more clear
```suggestion
  handleClick: () => object,
```

2023-03-29 21:56 UTC, hanahhleee commented on mobile/components/CustomButton/DataEntry.tsx
> +  const [date, setDate]: any = useState(month.toString() + "/" + day.toString() + "/" + year.toString());
It doesn't seem to like it when I explicitly type it as a string. I'm thinking that the type of the useState() auto-types it to be a string, but I might be wrong?

2023-03-29 21:58 UTC, hanahhleee commented on mobile/App.tsx
> +        <PhoneAuth config={firebaseConfig} auth={auth} />
When I get rid of the auth component, it raises a Render Error that says "Firebase: Need to provide options, when not being deployed to hosting via source", which is why I left it there. Is there a way around this?

2023-04-11 01:57 UTC, merged